name: Build Dash Component

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm dependencies
      run: |
        cd react-component
        npm install

    - name: Build React component
      run: |
        cd react-component
        npm run build

    - name: Install dash-generate-components
      run: npm install -g dash-generate-components

    - name: Generate Python bindings
      run: |
        npx dash-generate-components react-component dash_mention_textarea

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python deps
      run: pip install .

    - name: Run Python tests (optional)
      run: |
        echo "✅ Python installed and bindings generated!"
